FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates g++ cmake wget git curl gnupg lsb-release \
    libmemcached-dev automake bison flex libboost-all-dev libevent-dev \
    libssl-dev libtool make pkg-config librabbitmq-dev python3-dev \
  && wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/llvm.asc \
  && echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main" > /etc/apt/sources.list.d/llvm.list \
  && apt-get update && apt-get install -y --no-install-recommends clang-19 llvm-19 \
  && rm -rf /var/lib/apt/lists/*
RUN cd /tmp \
  && wget -q https://github.com/mongodb/mongo-c-driver/releases/download/1.15.0/mongo-c-driver-1.15.0.tar.gz \
  && tar -zxf mongo-c-driver-1.15.0.tar.gz && cd mongo-c-driver-1.15.0 \
  && cmake -B b -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=0 -DENABLE_EXAMPLES=0 -DCMAKE_C_FLAGS=-Wno-error . \
  && make -C b -j$(nproc) && make -C b install && rm -rf /tmp/*
RUN cd /tmp \
  && wget -qO thrift.tar.gz https://github.com/apache/thrift/archive/v0.12.0.tar.gz \
  && tar -zxf thrift.tar.gz && cd thrift-0.12.0 \
  && cmake -B b -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=0 -DBUILD_TUTORIALS=0 -DBUILD_PYTHON=0 -DBUILD_JAVA=0 -DBUILD_JAVASCRIPT=0 -DBUILD_NODEJS=0 -DCMAKE_CXX_FLAGS="-Wno-error -Wno-deprecated-declarations" . \
  && make -C b -j$(nproc) && make -C b install && rm -rf /tmp/*
RUN cd /tmp \
  && wget -qO json.tar.gz https://github.com/nlohmann/json/archive/v3.6.1.tar.gz \
  && tar -zxf json.tar.gz && cd json-3.6.1 \
  && cmake -B b -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=0 . \
  && make -C b -j$(nproc) && make -C b install && rm -rf /tmp/*
RUN cd /tmp \
  && wget -qO yaml.tar.gz https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz \
  && tar -zxf yaml.tar.gz && cd yaml-cpp-yaml-cpp-0.6.2 \
  && cmake -B b -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fPIC -DYAML_CPP_BUILD_TESTS=0 . \
  && make -C b -j$(nproc) && make -C b install && rm -rf /tmp/*
RUN cd /tmp \
  && wget -qO ot.tar.gz https://github.com/opentracing/opentracing-cpp/archive/v1.5.1.tar.gz \
  && tar -zxf ot.tar.gz && cd opentracing-cpp-1.5.1 \
  && cmake -B b -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fPIC -DBUILD_TESTING=0 . \
  && make -C b -j$(nproc) && make -C b install && rm -rf /tmp/*
RUN cd /tmp \
  && wget -qO jaeger.tar.gz https://github.com/jaegertracing/jaeger-client-cpp/archive/v0.4.2.tar.gz \
  && tar -zxf jaeger.tar.gz && cd jaeger-client-cpp-0.4.2 \
  && cmake -B b -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fPIC -Wno-error" -DHUNTER_ENABLED=0 -DBUILD_TESTING=0 -DJAEGERTRACING_WITH_YAML_CPP=1 -DJAEGERTRACING_BUILD_EXAMPLES=0 . \
  && make -C b -j$(nproc) && make -C b install && rm -rf /tmp/*
RUN cd /tmp \
  && wget -qO jwt.tar.gz https://github.com/arun11299/cpp-jwt/archive/v1.1.1.tar.gz \
  && tar -zxf jwt.tar.gz && cd cpp-jwt-1.1.1 \
  && cp -R include/jwt /usr/local/include \
  && rm -rf /usr/local/include/jwt/json \
  && sed -i 's/#include "jwt\/json\/json.hpp"/#include <nlohmann\/json.hpp>/g' /usr/local/include/jwt/jwt.hpp \
  && rm -rf /tmp/*
RUN ldconfig
